/* eslint-disable require-jsdoc */
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { HomeCointainer } from "../../styles/components/home/home";
import { getSession } from "next-auth/react";
import Layout from "../../components/Layout";
import { Fragment } from "react";
import { Menu, Transition } from "@headlessui/react";
import { CollectionsGrid } from "../../styles/components/collections/grid";
import "react-circular-progressbar/dist/styles.css";
import Collection from "../../components/Collections/Collection";
const Collections: NextPage = () => {
  //   const { data: session } = useSession();
  return (
    <>
      <Head>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCointainer className="body">
        <Layout>
          <div className="page_overview flex w-full justify-between items-start h-24">
            <h4 className="text-white font-medium text-xl">Collections</h4>
            <Menu as="div" className="relative inline-block">
              <div>
                <Menu.Button className="inline-flex justify-center w-full text-sm font-medium focus:outline-none focus-visible:ring-opacity-75">
                  <i className="bx bx-dots-horizontal-rounded cursor-pointer text-gray-400 text-2xl"></i>
                </Menu.Button>
              </div>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute right-0  w-56 origin-top-right todo-bg-header divide-y divide-blue-300/[.10] ring-1 rounded-xl shadow-lg ring-black ring-opacity-5 focus:outline-none">
                  <div className="px-1 py-1">
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          className={`${
                            active ? "bgmenucolor text-white" : "text-white"
                          } group flex rounded-xl items-center w-full py-3 text-sm `}
                        >
                          <span className="ml-3">Add a new Collection</span>
                        </button>
                      )}
                    </Menu.Item>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
          </div>
          <div className="page_treatment flex w-full flex-col justify-start items-start">
            <div className="page-filter-options w-full flex items-center justify-start">
              <button
                id="statistics"
                className=" mr-4 pr-7 pl-7 h-11 border-[#414052] border-2 rounded-2xl font-medium cursor-pointer text-white text-base"
              >
                Favorites
              </button>
              <button
                id="daily_overview"
                className=" pr-7 pl-7 h-12 bg-[#414052] rounded-2xl font-medium text-white text-base cursor-pointer"
              >
                All Collections
              </button>
            </div>
          </div>
          <CollectionsGrid className="grid w-full justify-center mt-8 ease-in mb-8">
            <Collection
              groupnane="School"
              groupicon="book"
              groupprogress={4}
              groupmax={6}
              groupcolor="#e743a3"
            />
            <Collection
              groupnane="Games"
              groupicon="dizzy"
              groupprogress={13}
              groupmax={13}
              groupcolor="#e7bb43"
            />
            <Collection
              groupnane="Code"
              groupicon="code-alt"
              groupprogress={2}
              groupmax={9}
              groupcolor="#e64f4f"
            />
            <Collection
              groupnane="Encomendas"
              groupicon="package"
              groupprogress={5}
              groupmax={5}
              groupcolor="#4f8cd1"
            />
            <Collection
              groupnane="Travels"
              groupicon="world"
              groupprogress={3}
              groupmax={6}
              groupcolor="#44a15c"
            />
          </CollectionsGrid>
        </Layout>
      </HomeCointainer>
    </>
  );
};

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
export default Collections;
