/* eslint-disable require-jsdoc */
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { HomeCointainer } from "../styles/components/home";
import { Fragment } from "react";
import { Menu, Transition } from "@headlessui/react";
import TodoItem from "../components/Todo_Item";
import Todo from "../components/Todo";
import { useSession } from "next-auth/react";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <div>
      <Head>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCointainer className="body ">
        <main>
          <Navbar />
          <section id="main-content">
            <Sidebar />
            <div id="closesidebar" className="android"></div>
            <section id="notes_section" className="flex items-center flex-col ">
              <div
                id="dashboard-page-content"
                className="w-full max-w-3xl flex items-start justify-start mt-10 overflow-y-auto"
              >
                {session ? (
                  <div className="mr-7 ml-7 w-full dash-margins">
                    <div className="page_overview flex w-full justify-between items-center">
                      <h4 className="text-white font-medium text-xl">
                        Dashboard
                      </h4>
                      <Menu as="div" className="relative inline-block">
                        <div>
                          <Menu.Button className="inline-flex justify-center w-full text-sm font-medium focus:outline-none focus-visible:ring-opacity-75">
                            <i className="bx bx-dots-horizontal-rounded cursor-pointer text-gray-400 text-2xl"></i>
                          </Menu.Button>
                        </div>
                        <Transition
                          as={Fragment}
                          enter="transition ease-out duration-100"
                          enterFrom="transform opacity-0 scale-95"
                          enterTo="transform opacity-100 scale-100"
                          leave="transition ease-in duration-75"
                          leaveFrom="transform opacity-100 scale-100"
                          leaveTo="transform opacity-0 scale-95"
                        >
                          <Menu.Items className="absolute right-0  w-56 origin-top-right todo-bg-header divide-y divide-blue-300/[.10] ring-1 rounded-xl shadow-lg ring-black ring-opacity-5 focus:outline-none">
                            <div className="px-1 py-1">
                              <Menu.Item>
                                {({ active }) => (
                                  <button
                                    className={`${
                                      active
                                        ? "bgmenucolor text-white"
                                        : "text-white"
                                    } group flex rounded-xl items-center w-full py-3 text-sm `}
                                  >
                                    <span className="ml-3">
                                      Change View Mode
                                    </span>
                                  </button>
                                )}
                              </Menu.Item>
                            </div>
                          </Menu.Items>
                        </Transition>
                      </Menu>
                    </div>
                    <div className="page_treatment flex w-full flex-col justify-start items-start">
                      <h2 className="text-white text-4xl mt-14 font-bold">
                        Good morning,
                        <br />
                        {session ? session.user!.name : "Not Logged In"}
                      </h2>
                      <div className="page-filter-options w-full flex items-center justify-start mt-14">
                        <button
                          id="daily_overview"
                          className="mr-4 pr-7 pl-7 h-12 bg-[#414052] rounded-2xl font-medium text-white text-base"
                        >
                          Daily Overview
                        </button>
                        <button
                          id="statistics"
                          className=" pr-7 pl-7 h-11 border-[#414052] border-2 rounded-2xl font-medium text-white text-base"
                        >
                          Statistic
                        </button>
                      </div>
                    </div>

                    <section
                      id="todos"
                      className="flex w-full flex-col items-center mt-10 mb-10"
                    >
                      <Todo
                        groupcolor="#997de7"
                        groupname="Travels"
                        iconname="paper-plane"
                      >
                        <TodoItem
                          groupcolor="#997de7"
                          itemcontent="Ir para São Paulo"
                          itemtime="2022-04-02"
                          checked={false}
                        />

                        <TodoItem
                          groupcolor="#997de7"
                          itemcontent="Cabo Frio com o Nego e com o Bielll 🥳🪅🎉"
                          itemtime="2022-02-21"
                          checked={false}
                        />
                        <TodoItem
                          groupcolor="#997de7"
                          itemcontent="Assistir Homem Aranha com Julia, já tá na hora"
                          itemtime="2021-12-28"
                          checked={false}
                        />
                      </Todo>

                      <Todo
                        groupcolor="#ee8b61"
                        groupname="Code"
                        iconname="code-alt"
                      >
                        <TodoItem
                          groupcolor="#ee8b61"
                          itemcontent="Como fazer maconha com maizena e javascript 🍂"
                          itemtime="2021-12-21"
                        />

                        <TodoItem
                          groupcolor="#ee8b61"
                          itemcontent="Procurar esse tal de java pra pedir umas dicas"
                          itemtime="2021-10-21"
                          checked={true}
                        />
                        <TodoItem
                          groupcolor="#ee8b61"
                          itemcontent="Não tenho dinheiro para comprar açaí 😢"
                          itemtime="2021-12-22"
                        />
                      </Todo>

                      <Todo
                        groupcolor="#fc76a1"
                        groupname="Games"
                        iconname="game"
                      >
                        <TodoItem
                          groupcolor="#fc76a1"
                          itemcontent="Dormir até desmaiar"
                          itemtime="2022-01-22"
                        />

                        <TodoItem
                          groupcolor="#fc76a1"
                          itemcontent="Matar o toriel de manhã se não programar nada 😳"
                          itemtime="2021-11-21"
                        />
                        <TodoItem
                          groupcolor="#fc76a1"
                          itemcontent="Dormir até desmaiar"
                          itemtime="2021-12-28"
                        />
                      </Todo>
                    </section>
                  </div>
                ) : (
                  ""
                )}
              </div>
            </section>
          </section>
        </main>
      </HomeCointainer>
    </div>
  );
};
if (typeof window !== "undefined") {
  const btn: any = document.getElementById("btn");
  const sidebar: any = document.getElementById("sidebar");
  const content: any = document.getElementById("notes_section");
  const close: any = document.getElementById("closesidebar");
  const main: any = document.querySelector("main");

  btn.onclick = function () {
    sidebar.classList.toggle("active");
    content.classList.toggle("active");
    close.classList.toggle("active");
    main.classList.toggle("active");
    main.classList.toggle("body");
  };

  close.onclick = function () {
    sidebar.classList.toggle("active");
    content.classList.toggle("active");
    close.classList.toggle("active");
    main.classList.toggle("active");
    main.classList.toggle("body");
  };
}

export default Home;
